name: Build and publish Docker image to GHCR
on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push image
        run: |
          docker login --username bilal-a-g --password ${{secrets.GH_TOKEN}} ghcr.io
          docker build . --tag ghcr.io/bilal-a-g/resume-personalizer:latest
          docker push ghcr.io/bilal-a-g/resume-personalizer:latest
